[features]
seeds = false
[programs.devnet]
solana_crowdfund_dapp_pda = "H9LXFGcGXhvdrNqAkULWnN2ByxEzFzVqJQMvYQWVTfUj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/abdullah/solana/solana-crowdfund-dapp-pda/my-solana-wallet/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
